# Generated by Django 4.0.3 on 2022-04-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='momentphoto',
            name='publication_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
