# Generated by Django 4.0.3 on 2022-04-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_venue_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ticket_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
